-- Tabella AGENTI
CREATE SEQUENCE agents_seq;
CREATE TABLE  AGENTS(
    AGENT_CODE TEXT NOT NULL DEFAULT concat('A', to_char(nextval('agents_seq'), '000FM')) PRIMARY KEY,
    AGENT_NAME TEXT,
    WORKING_AREA TEXT,
    COMMISSION NUMERIC(10,2),
    PHONE_NO TEXT,
    COUNTRY TEXT
);
ALTER SEQUENCE agents_seq OWNED BY AGENTS.AGENT_CODE;


-- Tabella CLIENTI
CREATE SEQUENCE customers_seq;
CREATE TABLE  CUSTOMERS(
    CUST_CODE TEXT NOT NULL DEFAULT concat('C', to_char(nextval('customers_seq'), '00000FM')) PRIMARY KEY,
    CUST_NAME TEXT NOT NULL,
    CUST_CITY TEXT,
    WORKING_AREA TEXT NOT NULL,
    CUST_COUNTRY TEXT NOT NULL,
    GRADE INT,
    OPENING_AMT NUMERIC(12,2) NOT NULL,
    RECEIVE_AMT NUMERIC(12,2) NOT NULL,
    PAYMENT_AMT NUMERIC(12,2) NOT NULL,
    OUTSTANDING_AMT NUMERIC(12,2) NOT NULL,
    PHONE_NO TEXT NOT NULL,
    AGENT_CODE TEXT NOT NULL REFERENCES AGENTS
);

ALTER SEQUENCE customers_seq OWNED BY CUSTOMERS.CUST_CODE;


-- Tabella ORDINI
CREATE SEQUENCE orders_seq
INCREMENT 1
START 200100;

CREATE TABLE  ORDERS(
    ORD_NUM INT NOT NULL DEFAULT nextval('orders_seq') PRIMARY KEY,
    ORD_AMT NUMERIC(12,2) NOT NULL,
    ADVANCE_AMT NUMERIC(12,2) NOT NULL,
    ORD_DATE DATE NOT NULL,
    CUST_CODE TEXT NOT NULL REFERENCES CUSTOMERS,
    AGENT_CODE TEXT NOT NULL REFERENCES AGENTS,
    ORD_DESCRIPTION TEXT NOT NULL
);
ALTER SEQUENCE orders_seq OWNED BY ORDERS.ORD_NUM;
