-- Tabella AGENTI
CREATE SEQUENCE agents_seq;
CREATE TABLE  AGENTS(
    AGENT_CODE CHAR(4) NOT NULL DEFAULT concat('A', to_char(nextval('agents_seq'), '000FM')) PRIMARY KEY,
    AGENT_NAME CHAR(40),
    WORKING_AREA CHAR(35),
    COMMISSION NUMERIC(10,2),
    PHONE_NO CHAR(15),
    COUNTRY CHAR(25)
);
ALTER SEQUENCE agents_seq OWNED BY AGENTS.AGENT_CODE;


-- Tabella CLIENTI
CREATE SEQUENCE customers_seq;
CREATE TABLE  CUSTOMERS(
    CUST_CODE CHAR(6) NOT NULL DEFAULT concat('C', to_char(nextval('customers_seq'), '00000FM')) PRIMARY KEY,
    CUST_NAME CHAR(40) NOT NULL,
    CUST_CITY CHAR(35),
    WORKING_AREA CHAR(35) NOT NULL,
    CUST_COUNTRY CHAR(20) NOT NULL,
    GRADE INT,
    OPENING_AMT NUMERIC(12,2) NOT NULL,
    RECEIVE_AMT NUMERIC(12,2) NOT NULL,
    PAYMENT_AMT NUMERIC(12,2) NOT NULL,
    OUTSTANDING_AMT NUMERIC(12,2) NOT NULL,
    PHONE_NO CHAR(17) NOT NULL,
    AGENT_CODE CHAR(6) NOT NULL REFERENCES AGENTS
);

ALTER SEQUENCE customers_seq OWNED BY CUSTOMERS.CUST_CODE;


-- Tabella ORDINI
CREATE SEQUENCE orders_seq
INCREMENT 1
START 200100;

CREATE TABLE  ORDERS(
    ORD_NUM NUMERIC(6,0) NOT NULL DEFAULT nextval('orders_seq') PRIMARY KEY,
    ORD_AMOUNT NUMERIC(12,2) NOT NULL,
    ADVANCE_AMOUNT NUMERIC(12,2) NOT NULL,
    ORD_DATE DATE NOT NULL,
    CUST_CODE CHAR(6) NOT NULL REFERENCES CUSTOMERS,
    AGENT_CODE CHAR(6) NOT NULL REFERENCES AGENTS,
    ORD_DESCRIPTION CHAR(60) NOT NULL
);
ALTER SEQUENCE orders_seq OWNED BY ORDERS.ORD_NUM;
